=== florian-cassagne/master-recettes-xml/recette.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Recettes ( Recette*, Auteur*,
    Ingredient*, Produit*, Categorie*, SousCategorie*
) >

<!ATTLIST Recette
        id ID #REQUIRED
        difficulte (tres-facile|facile|moyen|difficile) #IMPLIED>

<!ELEMENT Recette (Titre, Resume?, Photo?,
    Date, Quantite?, TempsPrepa?, TempsCuisson?,
    TempsRepos?, AuteurRef, IngredientRef*, DescriptionPrepa,
    Note?, Parametre*) >

<!ELEMENT Titre ( #PCDATA ) >
<!ELEMENT Resume ( #PCDATA ) >
<!ELEMENT Photo ( #PCDATA ) >
<!ELEMENT Date ( #PCDATA ) >
<!ELEMENT Difficulte ( #PCDATA ) >
<!ELEMENT Quantite ( #PCDATA ) >
<!ELEMENT TempsPrepa ( #PCDATA ) >
<!ELEMENT TempsCuisson ( #PCDATA ) >
<!ELEMENT TempsRepos ( #PCDATA ) >
<!ELEMENT DescriptionPrepa ( p | ul| table )* >
<!ELEMENT Note ( #PCDATA ) >

<!ATTLIST RecetteRef ref IDREF #REQUIRED >
<!ELEMENT RecetteRef EMPTY >


<!ELEMENT Ingredient ( Nom, ApportNutritif?,
    ApportEnergetique?, Saison?, Descriptif?,
    ProduitRef?, RecetteRef*, Parametre*) >
<!ATTLIST Ingredient id ID #REQUIRED >

<!ELEMENT Nom ( #PCDATA ) >
<!ELEMENT ApportNutritif ( #PCDATA ) >
<!ELEMENT ApportEnergetique ( #PCDATA ) >
<!ELEMENT Saison ( #PCDATA ) >
<!ELEMENT Descriptif ( #PCDATA )>

<!ELEMENT IngredientRef ( #PCDATA ) >
<!ATTLIST IngredientRef ref IDREF #REQUIRED >


<!ATTLIST Auteur id ID #REQUIRED>
<!ATTLIST Auteur sexe (h|f|n) #REQUIRED>
<!ELEMENT Auteur ( Nom, Age, Pays, Biographie, Parametre*, RecetteRef* ) >
<!ELEMENT Age ( #PCDATA) >
<!ELEMENT Pays ( #PCDATA) >
<!ELEMENT Biographie ( #PCDATA) >

<!ATTLIST AuteurRef ref IDREF #REQUIRED >
<!ELEMENT AuteurRef EMPTY >


<!ATTLIST Categorie id ID #REQUIRED >
<!ELEMENT CategorieRef EMPTY >
<!ATTLIST CategorieRef ref IDREF #REQUIRED >
<!ELEMENT SousCategorieRef EMPTY >
<!-- TODO : changer implied en required (Ã  voir ?) -->
<!ATTLIST SousCategorieRef refs IDREFS #IMPLIED >
<!ELEMENT Categorie ( Nom, Descriptif, Parametre*
        ) >
<!ELEMENT SousCategorie ( Nom, Descriptif?,
        CategorieRef, RecetteRef*, Parametre*
        ) >
<!ATTLIST SousCategorie id ID #REQUIRED >

<!ELEMENT Produit ( Nom ) >
<!ATTLIST Produit id ID #REQUIRED >
<!ELEMENT ProduitRef EMPTY >
<!ATTLIST ProduitRef produit IDREF #REQUIRED >

<!ELEMENT Parametre (#PCDATA)>

<!ELEMENT p ( #PCDATA | a | b | i )*>
<!ELEMENT ul ( li )*>
<!ELEMENT li ( #PCDATA | a | b | i )*>
<!ELEMENT table ( tr )+>
<!ELEMENT tr ( th | td )+>
<!ELEMENT th ( #PCDATA |a | b | i )*>
<!ELEMENT td ( #PCDATA | a | b | i )*>
<!ELEMENT b ( #PCDATA )>
<!ELEMENT i ( #PCDATA )>
<!ELEMENT a ( #PCDATA )>
<!ATTLIST a href CDATA #IMPLIED>

=== florian-cassagne/master-recettes-xml/recette.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Recettes SYSTEM "recette.dtd">
<?xml-stylesheet type="text/xsl"
    href="recette.xslt"?>

<Recettes
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="recette.xsd">

  <Recette id="citronnade" difficulte="tres-facile">
    <Titre>Citronnade</Titre>
    <Resume>L’atmosphère est lourd, le soleil brûle, ce temps est parfait pour une bonne citronnade pour vous rafraichir. Bien qu’on ne sache pas qui a inventé la citronnade, on sait que cette dernière trouve son origine dans l’Égypte du XIIe siècle : une recette qui ne date pas d’hier, donc, et qui a pu être perfectionnée avec les années, jusqu’à devenir cette boisson que nous aimons tant. Vous n’aurez pas à vous demander comment en enlever le goût amer, puisque le sirop de sucre l’évitera naturellement !</Resume>
    <Photo>https://odelices.ouest-france.fr/images/recettes/citronnade-1-820x1169.jpg</Photo>
    <Date>2022/08/04</Date>
    <Quantite>4 personnes</Quantite>
    <TempsPrepa>15 min</TempsPrepa>
    <TempsCuisson>2 min</TempsCuisson>
    <TempsRepos>2 H</TempsRepos>
    <AuteurRef ref="marie-laure-tombini" />
    <IngredientRef ref="citron_bio">
      3 citrons bio
    </IngredientRef>
    <IngredientRef ref="eau">
      40 cl d'eau
    </IngredientRef>
    <IngredientRef ref="sucre">
      80 g de sucre
    </IngredientRef>
    <DescriptionPrepa>
      <ul>
        <li>1. Dans une casserole, faites chauffer 40 cl d’eau avec le sucre.
          Laissez complètement refroidir.
        </li>
        <li>2. Pressez les citrons.
        </li>
        <li>3. Dans une carafe, mélangez le jus de citron avec le sirop de sucre et remuez bien.
        </li>
        <li>4. Placez la citronnade au réfrigérateur au moins 1h.
        </li>
        <li>5. Décorez de rondelles de citrons bio au moment de servir
        </li>
      </ul>
    </DescriptionPrepa>
    <Note>4</Note>
  </Recette>

  <Recette id="muffins-myrtilles-banane"
           difficulte="facile">
    <Titre>Muffins myrtilles banane</Titre>
    <Photo>https://odelices.ouest-france.fr/images/recettes/muffins_myrtilles_banane-970x1024.jpg</Photo>
    <Date>2015/08/03</Date>
    <TempsPrepa>15 min</TempsPrepa>
    <TempsCuisson>25 min</TempsCuisson>
    <AuteurRef ref="margot" />
    <IngredientRef ref="farine">
      100 g de farine
    </IngredientRef>
    <IngredientRef ref="maizena">
      50 g de maïzena
    </IngredientRef>
    <IngredientRef ref="levure_chimique">
      1 cuillerée à soupe de levure chimique
    </IngredientRef>
    <IngredientRef ref="oeuf">
      1 œuf
    </IngredientRef>
    <IngredientRef ref="beurre">
      50 g de beurre
    </IngredientRef>
    <IngredientRef ref="lait">
      4 cl de lait
    </IngredientRef>
    <IngredientRef ref="sucre">
      70 g de sucre
    </IngredientRef>
    <IngredientRef ref="myrtille">
      150 g de myrtilles
    </IngredientRef>
    <IngredientRef ref="banane">
      75 g de banane
    </IngredientRef>
    <IngredientRef ref="eau_rose">
      1 cuillerée à soupe d'eau de rose
    </IngredientRef>
    <DescriptionPrepa>
      <ul>
        <li>1. Mélangez la farine, la maïzena, la levure et le sucre.</li>
        <li>2. Incorporez l’œuf, puis le beurre fondu le lait et l’eau de rose.</li>
        <li>3. Incorporez délicatement les myrtilles et la banane coupée en dés.</li>
        <li>4. Versez dans des caissettes à muffins.</li>
        <li>5. Faites cuire 20 à 25mn dans le four préchauffé à 180°C.</li>
      </ul>
    </DescriptionPrepa>
  </Recette>

  <Recette id="tarte-betterave-pesto"
           difficulte="moyen">
    <Titre>Tarte fine à la betterave et pesto d’herbes</Titre>
    <Resume>Si vous trouvez un beau bouquet de persil, je vous conseille cette fabuleuse recette de tarte fine : j’ai eu l’idée de faire un pesto très parfumé aux herbes pour en tartiner une pâte à tarte et de la garnir de rondelles de betterave. Une recette très originale et vraiment savoureuse !</Resume>
    <Photo>https://odelices.ouest-france.fr/images/recettes/tarte-fine-betterave-pesto3-932x1250.jpg</Photo>
    <Date>2015/08/03</Date>
    <Quantite>6 personnes</Quantite>
    <TempsPrepa>15 min</TempsPrepa>
    <TempsCuisson>25 min</TempsCuisson>
    <AuteurRef ref="marie-laure-tombini" />
    <IngredientRef ref="persil">
      20 g de persil
    </IngredientRef>
    <IngredientRef ref="parmesan">
      10 g de parmesan
    </IngredientRef>
    <IngredientRef ref="noix">
      10 g de noix
    </IngredientRef>
    <IngredientRef ref="huile">
      5 g d'huile
    </IngredientRef>
    <IngredientRef ref="chevre">
      100 g de chèvre frais
    </IngredientRef>
    <IngredientRef ref="betterave">
      200 g de betterave cuites
    </IngredientRef>
    <IngredientRef ref="pate-feuilletee">
      1 pâte feuilletée
    </IngredientRef>
    <DescriptionPrepa>
      <ul>
        <li>1. Mixez le persil, le parmesan, les noix et l’huile jusqu’à obtenir une pâte.</li>
        <li>2. Ajoutez le chèvre frais, mélangez.</li>
        <li>3. Coupez les betteraves en tranches.</li>
        <li>4. Déroulez la pâte feuilletée sur une plaque à four, tartinez de crème au chèvre en laissant un bord libre de 2 cm, répartissez dessus les tranches de betteraves.</li>
        <li>5. Faites cuire 25 min dans un four préchauffé à 180 °C.</li>
        <li>6. Agrémentez avec persil, noix concassées, lamelles de parmesan et un trait d’huile.</li>
      </ul>
    </DescriptionPrepa>
    <Note>5</Note>
  </Recette>

  <Recette id="canneles-lardons"
           difficulte="facile">
    <Titre>Délicieux cannelés aux lardons pour votre soirée foot</Titre>
    <Resume>Recette mise à jour le 22 juin 2018
      Photo de la recette : Délicieux cannelés aux lardons pour votre soirée foot
      J’ai comme l’impression que les apéros canap vont se multiplier ces prochains jours avec les matchs de la coupe du monde… Ce n’est pas un évènement que je suis mais peut-être cherchez-vous des idées pour varier les recettes de l’apéritif ? Je vous propose des cannelés aux lardons, largement plébiscités par ma fille et mon mari ! A découvrir aussi : toutes nos recettes de cannelés salés.</Resume>
    <Photo>https://odelices.ouest-france.fr/images/recettes/canneles-lardons-753x1024.jpg.webp</Photo>
    <Date>2018/06/22</Date>
    <Quantite>25 cannelés</Quantite>
    <TempsPrepa>10 min</TempsPrepa>
    <TempsCuisson>35 min</TempsCuisson>
    <AuteurRef ref="marie-laure-tombini" />
    <IngredientRef ref="poulet">
      4 morceaux de poulet
    </IngredientRef>
    <IngredientRef ref="poivron-rouge">
      1 poivron rouge
    </IngredientRef>
    <IngredientRef ref="poivron-orange">
      1 poivron orange
    </IngredientRef>
    <IngredientRef ref="tomate">
      200 g de tomates pelées et concassées en dés
    </IngredientRef>
    <IngredientRef ref="champignon">
      200 g de champignons
    </IngredientRef>
    <IngredientRef ref="oignon">
      2 oignons
    </IngredientRef>
    <IngredientRef ref="sel">
      Sel
    </IngredientRef>
    <IngredientRef ref="piment-espelette">
      Piment d'Espelette
    </IngredientRef>
    <DescriptionPrepa>
      <ul>
        <li>1. Salez et poivrez les morceaux de poulet, puis faites-les revenir 5 min sur chaque face dans une sauteuse légèrement huilée. Réservez dans une assiette.</li>
        <li>2. Coupez finement les oignons, puis ajoutez-les à la sauteuse pour les faire revenir quelques instants.</li>
        <li>3. Une fois vos champignons lavés et coupés en quatre, faites les cuire 5′ min dans la sauteuse, puis réservez.</li>
        <li>4. Lavez et épépinez vos poivron, puis coupez-les en lanières et déposez-les dans la sauteuse.</li>
        <li>5. Ajoutez les tomates concassées et couvez pour laisser mijoter pendant 10 min.</li>
        <li>6. Déposez les morceaux de poulet et les champignons et laissez mijoter 10 min de plus.</li>
        <li>7. Servez bien chaud, avec du riz. Bon appétit !</li>
      </ul>
    </DescriptionPrepa>
  </Recette>

  <Recette id="poulet-basquaise-champignons-poivrons"
           difficulte="facile">
    <Titre>Poulet basquaise aux champignons et poivrons</Titre>
    <Resume>Incontournable de la cuisine française, et plus particulièrement basque, le poulet basquaise est une recette qui consiste à faire mijoter du poulet dans un mélange de sauce confite de poivrons rouges et verts, de tomates, d’ail, d’oignons, entre autres, que l’on nomme piperade. Tout comme la pizza Margherita est l’emblème de l’Italie car elle est aux couleurs du drapeau italien, le poulet basquaise représente également le drapeau basque : le rouge et le vert grâce aux poivrons, le blanc apporté par le poulet. Il existe quelques variantes de ce plat, mais ce dernier reste inégalable et vous transportera jusque dans le sud ouest !</Resume>
    <Photo>https://odelices.ouest-france.fr/images/recettes/poulet-basquaise3-820x1230.jpg</Photo>
    <Date>2022/07/29</Date>
    <Quantite>25 cannelés</Quantite>
    <TempsPrepa>25 min</TempsPrepa>
    <TempsCuisson>40 min</TempsCuisson>
    <AuteurRef ref="margot" />
    <IngredientRef ref="oeuf">
      3 gros oeufs
    </IngredientRef>
    <IngredientRef ref="yaourt">
      1 yaourt (125 g)
    </IngredientRef>
    <IngredientRef ref="lait">
      10 cl de lait
    </IngredientRef>
    <IngredientRef ref="farine">
      70 g de farine de blé
    </IngredientRef>
    <IngredientRef ref="fromage">
      50 g de fromage râpé (emmental ou comté)
    </IngredientRef>
    <IngredientRef ref="lardons">
      50 g de lardons
    </IngredientRef>
    <DescriptionPrepa>
      <ul>
        <li>1. Dans un saladier, battez les oeufs en omelette. Fouettez avec le lait et le yaourt.</li>
        <li>2. Ajoutez la farine et mélangez bien. Puis incorporez le fromage et les lardons.</li>
        <li>3. Répartissez la préparation dans des moules à mini cannelés.</li>
        <li>4. Faites cuire environ 35 min dans le four préchauffé à 180°C.</li>
